project_id = "imeghpjrqlmifkltuqdx"

[functions.process-email-queue]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false