import { LegalLayout } from "./LegalLayout";

export default function AIDisclosure() {
  return (
    <LegalLayout
      title="AI Disclosure"
      updated="May 16, 2026"
      path="/legal/ai-disclosure"
      description="How EBLOCKI uses AI, which models, and what we don't do."
    >
      <p>
        EBLOCKI uses large language models to power the coach, the proof verdict engine, and OCR
        text extraction. This page describes how.
      </p>

      <h2>What is generated by AI</h2>
      <ul>
        <li>Coach replies in the chat interface.</li>
        <li>Proof artifact verdicts — score, feedback, suggested upgrade.</li>
        <li>OCR text extracted from uploaded PDFs and images.</li>
        <li>Behavioural state detection from the wording of your messages.</li>
      </ul>

      <h2>What is NOT generated by AI</h2>
      <ul>
        <li>Your control sheets, modes, and proof contracts — you author these.</li>
        <li>The streak engine and momentum scoring — deterministic code.</li>
      </ul>

      <h2>Models</h2>
      <p>We use these models via the Lovable AI Gateway:</p>
      <ul>
        <li>Google Gemini 2.5 / 3 family</li>
        <li>OpenAI GPT-5 family</li>
      </ul>
      <p>You can pick your preferred model under <strong>Settings → Preferred model</strong>.</p>

      <h2>Data sent to model providers</h2>
      <p>
        When you send a coach message or submit a proof artifact, the relevant text, your active
        mode, and the OCR text are sent to the model. We do not include your email, payment data,
        or other accounts in these prompts.
      </p>

      <h2>Training</h2>
      <p>Our gateway contract prohibits the use of customer prompts for model training.</p>

      <h2>Limitations</h2>
      <p>
        AI outputs can be wrong, biased, or hallucinated. Verdicts are guidance, not truth. Treat
        them as a sparring partner, not a verdict from a real judge.
      </p>
    </LegalLayout>
  );
}