import { LegalLayout } from "./LegalLayout";

export default function Terms() {
  return (
    <LegalLayout
      title="Terms of Service"
      updated="May 16, 2026"
      path="/legal/terms"
      description="The rules for using EBLOCKI."
    >
      <p>By creating an account on EBLOCKI you agree to these terms. If you do not agree, do not use the service.</p>

      <h2>1. The service</h2>
      <p>
        EBLOCKI is a behavioural performance operating system. It is a tool — not a medical,
        psychological, legal, financial, or academic-grading service. Verdicts, scoring, and
        coach responses are generated by software and do not constitute professional advice.
      </p>

      <h2>2. Your account</h2>
      <ul>
        <li>You must be at least 13 years old.</li>
        <li>You are responsible for keeping your credentials secure.</li>
        <li>One account per person. Sharing logins is not permitted.</li>
      </ul>

      <h2>3. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Upload content you do not have rights to.</li>
        <li>Upload content that is illegal, harassing, or infringing.</li>
        <li>Attempt to reverse-engineer the AI prompts, extract other users' data, or abuse the service.</li>
        <li>Use the service to build a competing product.</li>
      </ul>

      <h2>4. Your content</h2>
      <p>
        You retain ownership of every proof artifact, control sheet, and message you submit.
        You grant us a limited licence to store and process this content solely to operate the
        service for you.
      </p>

      <h2>5. AI output</h2>
      <p>
        Verdicts and coach output are produced by machine learning models and may be wrong.
        You are solely responsible for any decision you make based on them.
      </p>

      <h2>6. Suspension &amp; termination</h2>
      <p>
        We may suspend or terminate accounts that violate these terms. You may delete your account
        at any time from Settings → Account.
      </p>

      <h2>7. Disclaimer &amp; liability</h2>
      <p>
        The service is provided "as is". To the maximum extent permitted by law, our aggregate
        liability is limited to the fees you paid in the prior 12 months (currently zero for the
        free tier).
      </p>

      <h2>8. Changes</h2>
      <p>We may update these terms; material changes will be announced in-app.</p>

      <h2>9. Contact</h2>
      <p><a href="mailto:legal@eblocki.space">legal@eblocki.space</a></p>
    </LegalLayout>
  );
}