// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/check-proof-artifact.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import {
  buildRefusalPayload,
  checkAnalysisSafety,
  runProofCheck
} from "npm:@/lib/eblocki/proof-check";
var check_proof_artifact_default = defineTool({
  name: "check_proof_artifact",
  title: "Check proof artifact",
  description: "Judge pasted proof artifact text against Eblocki's rubric. Read-only. Does not access account data or verify external facts.",
  inputSchema: {
    artifact_text: z.string().min(1).describe("Pasted artifact text only. No files, links, or secrets."),
    goal: z.string().optional().describe("Optional claimed goal or completion statement."),
    domain_hint: z.string().optional().describe("Optional domain hint such as law, product, psychology, or general.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ artifact_text, goal, domain_hint }) => {
    const safety = { artifactText: artifact_text, goal, domainHint: domain_hint };
    if (checkAnalysisSafety(safety).blocked) {
      const refusal = buildRefusalPayload(safety);
      return {
        content: [{ type: "text", text: JSON.stringify(refusal) }],
        structuredContent: refusal,
        isError: true
      };
    }
    const result = runProofCheck({
      artifactText: artifact_text,
      goal,
      domainHint: domain_hint
    });
    const payload = {
      verdict: result.verdict,
      score: result.score,
      selected_standard: result.selectedStandard,
      standard_label: result.standardLabel,
      reasoning_summary: result.reasoningSummary,
      self_deception_risk: result.selfDeceptionRisk,
      limitations: result.limitations,
      read_only_notice: result.readOnlyNotice
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-proof-standard.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { getProofStandardLookup } from "npm:@/lib/eblocki/proof-check";
var get_proof_standard_default = defineTool2({
  name: "get_proof_standard",
  title: "Get proof standard",
  description: "Return Eblocki's rubric for a given goal/domain. Read-only. Does not access account data or persist anything.",
  inputSchema: {
    goal: z2.string().optional().describe("Optional task or goal description."),
    domain_hint: z2.string().optional().describe("Optional domain hint such as law, product, psychology, or general.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ goal, domain_hint }) => {
    const result = getProofStandardLookup({ goal, domainHint: domain_hint });
    const payload = {
      standard_key: result.standardKey,
      standard_label: result.standardLabel,
      required_evidence: result.requiredEvidence,
      missing_standard: result.missingStandard,
      elite_version: result.eliteVersion,
      next_upgrade: result.nextUpgrade
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/suggest-next-command.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
import {
  buildRefusalPayload as buildRefusalPayload2,
  checkAnalysisSafety as checkAnalysisSafety2,
  runProofCheck as runProofCheck2
} from "npm:@/lib/eblocki/proof-check";
var suggest_next_command_default = defineTool3({
  name: "suggest_next_command",
  title: "Suggest next command",
  description: "Return the next Eblocki proof command from supplied artifact text. Read-only. Does not access account history or write results.",
  inputSchema: {
    artifact_text: z3.string().min(1).describe("Pasted artifact text only."),
    goal: z3.string().optional().describe("Optional goal or claimed completion statement."),
    domain_hint: z3.string().optional().describe("Optional domain hint.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ artifact_text, goal, domain_hint }) => {
    const safety = { artifactText: artifact_text, goal, domainHint: domain_hint };
    if (checkAnalysisSafety2(safety).blocked) {
      const refusal = buildRefusalPayload2(safety);
      return {
        content: [{ type: "text", text: JSON.stringify(refusal) }],
        structuredContent: refusal,
        isError: true
      };
    }
    const result = runProofCheck2({
      artifactText: artifact_text,
      goal,
      domainHint: domain_hint
    });
    const payload = {
      next_command: result.nextCommand,
      recommended_artifact_type: result.recommendedArtifactType,
      proof_question: result.proofQuestion,
      mode_warning: result.modeWarning,
      read_only_notice: result.readOnlyNotice
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "eblocki-mcp",
  title: "Eblocki",
  version: "0.1.0",
  instructions: "Eblocki proof tools. Read-only. Judge pasted artifact text against Eblocki's evidence rubric; return proof standards and next commands. Never implies external verification, saved account access, or write actions.",
  tools: [check_proof_artifact_default, get_proof_standard_default, suggest_next_command_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
